export const USER_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_LENGTH: 'Name must be between 1 and 100 characters',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_IS_STRONG:
    'Password must be contain at least one uppercase letter, one lowercase letter, one number, and one special character',
  PASSWORD_LENGTH: 'Password must be between 8 and 50 characters',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_MATCH: 'Confirm password must match the password',
  DATE_OF_BIRTH_IS_REQUIRED: 'Date of birth is required',
  DATE_OF_BIRTH_IS8601_INVALID: 'Date of birth must be a valid ISO 8601 date',
  LOGIN_INCORRECT: 'Email or password is incorrect',
  LOGIN_SUCCESS: 'Login successfully',
  REGISTER_SUCCESS: 'Register successfully',
  UN_AUTHORIZATION: 'Unauthorized',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  LOGOUT_SUCCESS: 'Logout successfully',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  EMAIL_VERIFY_TOKEN_IS_INVALID: 'Email verify token is invalid',
  EMAIL_VERIFY_SUCCESS: 'Email verify successfully',
  EMAIL_VERIFY_FAILED: 'Email verify failed',
  EMAIL_WAS_VERIFIED: 'Email was verified',
  USER_NOT_FOUND: 'User not found',
  RESEND_VERIFY_EMAIL_SUCCESS: 'Resend verify email successfully',
  CHECK_EMAIL_TO_RESET_PASSWORD: 'Check email to reset password',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token is required',
  FORGOT_PASSWORD_TOKEN_IS_INVALID: 'Forgot password token is invalid',
  VERIFY_FORGOT_PASSWORD_TOKEN_SUCCESS: 'Verify forgot password token successfully',
  RESET_PASSWORD_SUCCESS: 'Reset password successfully',
  BIO_IS_STRING: 'Bio must be a string',
  BIO_LENGTH: 'Bio must be between 1 and 200 characters',
  LOCATION_IS_STRING: 'Location must be a string',
  LOCATION_LENGTH: 'Location must be between 1 and 200 characters',
  WEBSITE_IS_STRING: 'Website must be a string',
  WEBSITE_LENGTH: 'Website must be between 1 and 200 characters',
  USERNAME_IS_STRING: 'Username must be a string',
  USERNAME_INVALID: 'Username must be 1 to 15 characters long and only contain letters, numbers, or underscores',
  USERNAME_EXISTS: 'Username already exists',
  AVATAR_IS_STRING: 'Avatar must be a string',
  IMAGE_URL_IS_STRING: 'Image URL must be a string',
  IMAGE_URL_LENGTH: 'Image URL must be between 1 and 400 characters',
  UPDATE_PROFILE_SUCCESS: 'Update profile successfully',
  FOLLOWER_USER_ID_IS_NOT_EMPTY: 'Follower user ID is not empty',
  FOLLOW_SUCCESS: 'Follow successfully',
  CANNOT_FOLLOW_YOURSELF: 'Cannot follow yourself',
  ALREADY_FOLLOWING: 'Already following',
  UN_FOLLOW_SUCCESS: 'Unfollow successfully',
  HAVE_NOT_FOLLOWING: 'have not following user',
  CHANGE_PASSWORD_SUCCESS: 'Change password successfully',
  NEW_PASSWORD_IS_SAME_OLD_PASSWORD: 'New password must be different from the old password.',
  OLD_PASSWORD_IS_REQUIRED: 'Old password is required',
  OLD_PASSWORD_IS_WRONG: 'Old password is wrong',
  REFRESH_TOKEN_SUCCESS: 'Refresh token successfully',
  FORBIDDEN: 'Forbidden',
  USER_ID_REQUIRED: 'User ID is required',
  USER_ID_INVALID: 'User ID is invalid',
  REFRESH_TOKEN_IS_STRING: 'Refresh token must be a string',
  REFRESH_TOKEN_IS_INVALID: 'Refresh token is invalid'
}

export const RESTAURANT_MESSAGES = {
  ID_IS_STRING: 'Restaurant ID must be a string',
  CREATED_SUCCESS: 'Restaurant created successfully',
  UPDATED_SUCCESS: 'Restaurant updated successfully',
  DELETED_SUCCESS: 'Restaurant deleted successfully',
  LIST_FETCHED_SUCCESS: 'Restaurant list fetched successfully',
  NOT_FOUND: 'Restaurant not found',
  ID_IS_REQUIRED: 'Restaurant ID is required',
  ID_IS_INVALID: 'Restaurant ID is invalid',
  NAME_IS_REQUIRED: 'Restaurant name is required',
  NAME_LENGTH: 'Restaurant name must be between 1 and 100 characters',
  DESCRIPTION_IS_REQUIRED: 'Restaurant description is required',
  DESCRIPTION_LENGTH: 'Restaurant description must be between 1 and 500 characters',
  ADDRESS_IS_REQUIRED: 'Restaurant address is required',
  AVATAR_IS_REQUIRED: 'Restaurant avatar is required',
  PHONE_NUMBER_IS_REQUIRED: 'Restaurant phone number is required',
  PHONE_NUMBER_IS_INVALID: 'Restaurant phone number is invalid',
  WEBSITE_IS_STRING: 'Restaurant website must be a string',
  WEBSITE_LENGTH: 'Restaurant website must be between 1 and 200 characters',

  RATING_IS_NUMBER: 'Restaurant rating must be a number',
  RATING_MIN: 'Restaurant rating must be at least 0',
  RATING_MAX: 'Restaurant rating must be at most 5',
  RATING_DEFAULT: 'Restaurant rating defaults to 5 if not provided',
  RESTAURANT_NOT_FOUND: 'Restaurant not found',
  RESTAURANT_ALREADY_EXISTS: 'Restaurant with this name already exists',
  RESTAURANT_ID_IS_REQUIRED: 'Restaurant ID is required',
  RESTAURANT_ID_IS_INVALID: 'Restaurant ID is invalid',
  WEEKLY_OPENING_HOURS_IS_ARRAY: 'Weekly opening hours must be an array',
  WEEKLY_OPENING_HOURS_INVALID: 'Weekly opening hours must be valid objects',
  SPECIAL_OPENING_DAYS_IS_ARRAY: 'Special opening days must be an array',
  SPECIAL_OPENING_DAYS_INVALID: 'Special opening days must be valid objects',
  RATING_IS_INT: 'Restaurant rating must be from 1 to 5'
}

export const BOOKMARK_MESSAGES = {
  RESTAURANT_ID_REQUIRED: 'Restaurant ID is required',
  USER_ID_REQUIRED: 'User ID is required'
}

export const REVIEW_MESSAGES = {
  CONTENT_IS_REQUIRED: 'Review content is required',
  REVIEW_ID_INVALID: 'Review ID is invalid',
  CONTENT_LENGTH: 'Review content must be between 1 and 1000 characters',
  RATING_IS_NUMBER: 'Rating must be a number',
  RATING_MIN: 'Rating must be at least 1',
  RATING_MAX: 'Rating must be at most 5',
  RESTAURANT_ID_REQUIRED: 'Restaurant ID is required',
  USER_ID_REQUIRED: 'User ID is required',
  REVIEW_ID_REQUIRED: 'Review ID is required',
  UN_AUTHORIZATION: 'You do not have permission to delete this resource.'
}

export const COMMON = {
  PAGE_INVALID: 'Page must be a positive integer',
  PAGE_SIZE_INVALID: 'Page size must be a positive integer',
  LIMIT_INVALID: 'Limit must be a positive integer',
  LIMIT_MAX: 'Limit must not exceed 100',
  SORT_BY_INVALID: 'Sort by must be a valid field',
  SORT_ORDER_INVALID: 'Sort order must be either "asc" or "desc"',
  MEDIA_IS_ARRAY: 'Restaurant media must be an array',
  MEDIA_ITEM_INVALID: 'Each media item must be a valid object with type and url',
  MEDIA_ITEM_TYPE_INVALID: 'Media type must be one of the following: image, video, audio',
  MEDIA_ITEM_URL_INVALID: 'Media URL must be a valid URL',
  MEDIA_ITEM_URL_LENGTH: 'Media URL must be between 1 and 400 characters',
  MEDIA_ITEM_REQUIRED: 'At least one media item is required',
  MEDIA_ITEM_MAX: 'A maximum of 10 media items is allowed',
  MEDIA_ITEM_MIN: 'At least one media item is required',
  SEARCH_MUST_BE_STRING: 'Search must be a string',
  ID_IS_INVALID: 'ID is invalid',
  ID_IS_REQUIRED: 'ID is required',
  IS_ACTIVE_MUST_BE_BOOLEAN: 'isActive must be a boolean',
  ROLE_INVALID: 'Role is invalid'
}

export const ROLE_MESSAGES = {
  NAME_IS_REQUIRED: 'Role name is required',
  NAME_IS_INVALID: 'Role name must be a string',
  ROLE_IS_DUPLICATE: 'Role already exists',
  ROLE_ID_IS_REQUIRED: 'Role ID is required',
  ROLE_ID_IS_INVALID: 'Role ID is invalid'
}

export const MENU_MESSAGES = {
  RESTAURANT_IS_REQUIRED: 'Restaurant ID is required',
  RESTAURANT_ID_IS_INVALID: 'Restaurant ID is invalid',
  MENU_ID_IS_REQUIRED: 'Menu ID is required',
  MENU_ID_IS_INVALID: 'Menu ID is invalid',
  NAME_IS_REQUIRED: 'Menu name is required',
  NAME_IS_INVALID: 'Menu name must be a string',
  PRICE_IS_REQUIRED: 'Menu price is required',
  PRICE_IS_NUMBER: 'Menu price must be a number',
  PRICE_IS_INVALID: 'Menu price is invalid',
  DESCRIPTION_IS_REQUIRED: 'Menu description is required',
  DESCRIPTION_IS_INVALID: 'Menu description must be a string'
}
